### ISSUE TITLE
Document file descriptor limits

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/lotus-docs#215]
The lotus-storage-miner requires a much larger value for NOFILE than most operating systems default with. We should document this requirement. In my own testings I've found that the number is 16 per sealed sector minimum. This means for a full partition a miner needs 38400 to perform a Window PoSt. This is **not** the correct value and a much larger value should be set.

**Comment by rjan90** [comment]
Closing this now since we have a knowledge base article about the file descriptor limits: https://lotus.filecoin.io/kb/soft-fd-limit/. And its also clearly stated which subsystems needs a high file descriptor limit in their respective setup-pages (seal-workers, lotus-miner, post-workers)

Thanks again for the ticket.
