### ISSUE TITLE
Search function is broken. 

### ISSUE THREAD

**Issue by Reiers** [filecoin-project/lotus-docs#38]
## Search function is not working properly 

You can only do one search at the time. 
To fix it you have to go back to main site, or refresh the site.
(Hard to navigate, and causes problems for new onboarding users)

Reproduce:
`Search for something, go to that location. Search again - nothing shows up. `

**Comment by johnnymatthews** [comment]
Looking into this now.

**Comment by johnnymatthews** [comment]
This issue doesn't show up when running the site locally with `npm run build`, but does when it's hosted either on Fleek or Netlify. It even shows up when running `npm run build && cd public && serve` (required the [NPM package serve](https://www.npmjs.com/package/serve) to be installed globally). This makes me thing this issue is something to do with how the search function is configured when in production.

Still looking into this issue.

**Comment by johnnymatthews** [comment]
Being address in https://github.com/filecoin-project/lotus-docs/pull/39
