### ISSUE TITLE
Update `lotus-miner sectors renew` to `lotus-miner sectors extend`

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus-docs#526]
**Edited by @ElPaisano**

## Original description

Check the Lotus documentation for `lotus-miner sectors renew` and `lotus-miner sectors extend` cmds.

The `lotus-miner sectors extend` command has been refactored to have the features of `lotus-miner sectors renew` in v1.21.0. We need to update the docs accordingly

## Additional context 

(from a discussion with @rjan90)

- The functionality from `lotus-miner sectors renew` has been ported over to the `lotus-miner sectors extend `cmd. (meaning that the old `lotus-miner sectors extend` functionality has been removed.
- The` lotus-miner sectors renew` command has been deprecated.

I have added a kb-article that the `lotus-miner sectors renew` cmd has been removed: https://lotus.filecoin.io/kb/sectors-renew-cmd/
Lotus DocsLotus Docs
[Lotus-Miner Sectors renew command is removed from CLI](https://lotus.filecoin.io/kb/sectors-renew-cmd/)
The `lotus-miner sectors renew` command has been replaced by `lotus-miner sectors extend`

What is missing is combing through the docs, and updating `lotus-miner sectors extend` section with the new functionality, and possibly rename any mentions of `lotus-miner sectors renew` to `lotus-miner sectors extend`.

**Comment by ElPaisano** [comment]
So, as part of this PR, I think it would be good to add warnings to https://lotus.filecoin.io/storage-providers/operate/lotus-miner-cli/#lotus-miner-sectors-renew and https://lotus.filecoin.io/storage-providers/operate/lotus-miner-cli/#lotus-miner-sectors-extend explaining the change. However, it looks like this page is autogenerated? So, then:

1. Should I edit it at all?
2. If not, when will the page be updated? As a reader, it would be confusing to read https://lotus.filecoin.io/kb/sectors-renew-cmd/, then navigate to https://lotus.filecoin.io/storage-providers/operate/lotus-miner-cli/#lotus-miner-sectors-renew

Also, my `lotus-miner` cli (on version `1.19.0+mainnet+git.64059ca87`) still shows `renew` under `COMMANDS` - will this be updated as well?

**Comment by ElPaisano** [comment]
Actually, now that I think about it, as I'm looking through the files in the docs that mention `sector renew`, I'm running into stuff like https://lotus.filecoin.io/storage-providers/operate/daily-chores/#extend-sectors - basically, I'm not clear how `lotus-miner sectors extend` works as of this update (since it seems like I can't test it in the cli???), so I'm not sure how to update the `lotus-miner sectors renew` examples. 

In other words, does `lotus-miner sectors extend` have the same syntax it had before `lotus-miner sectors extend [command options] <sectorNumbers...>`, and the same flag options + the flag options that were formerly available in `lotus-miner sectors renew`? Or has the syntax changed i.e. `lotus-miner sectors extend [command options] [arguments...]` to match `renew` + `extend` only supports flags from `renew` and has dropped ALL of its old functionality?

Sorry if that's confusing, lmk if I can clarify anything.

Also, maybe I'm doing something wrong and just need to update my lotus-miner (I thought 1.19.0 was latest)? I'm a total lotus newb, so advice would be appreciated

**Comment by rjan90** [comment]
> However, it looks like this page is autogenerated? So, then:
> 1. Should I edit it at all?
> 2. If not, when will the page be updated? 

For the CLI-pages they are autogenerated yes. And we have a PR ready to go out here (https://github.com/filecoin-project/lotus-docs/pull/525) once the final v1.21.0 release is shipped.

**Comment by rjan90** [comment]
> Also, maybe I'm doing something wrong and just need to update my lotus-miner (I thought 1.19.0 was latest)? I'm a total lotus newb, so advice would be appreciated

The `lotus-miner sectors renew` --> `lotus-miner sectors extend` changes are coming in the v1.21.0 release, so it makes sense that you are not seeing these changes on v1.19.0 😄
