### ISSUE TITLE
Audit and Revise Lotus Section in Lotus docs

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/lotus-docs#79]
This issue is part of overall lotus docs audit project.

Goal - User should be able to run and maintain a lotus node/ lite node successfully with just this section of lotus-docs.

Check for content and correctness.
Validate all links
Add more relevant content if required.
Run all commands locally to verify input and output.
Add missing steps or variables and OS based information if needed.
Identify the opportunity and create new articles/solutions/blogs/tutorials.
Link relevant sections like architecture, filecoin-economics etc to filecoin docs to allow users to have access to all info from one place. This will require some research.

- [ ] What is Lotus
- [ ] Filecoin Networks
- [ ] Types of Lotus Node - TODO - Add local network links once developers sector has been audited
- [ ] Lotus Prerequisite
- [ ] Install on Linux
- [ ] Install on MacOS
- [ ] Running in cloud
- [ ] Lotus configuration
- [ ] Lite node
- [ ] Bootstrappers
- [ ] Manage FIL
- [ ] Multisig
- [ ] Chain management
- [ ] Switch networks
- [ ] Backup and restore a node
- [ ] Upgrade
- [ ] Troubleshooting
- [ ] CLI
- [ ] Contribute

**Comment by smagdali** [comment]
**Installing Lotus from [https://docs.filecoin.io/get-started/store-and-retrieve](https://docs.filecoin.io/get-started/store-and-retrieve)** 

We walked through these instructions:

[https://docs.filecoin.io/get-started/store-and-retrieve/](https://docs.filecoin.io/get-started/store-and-retrieve/)

Currently these issues prevent an easy install (even when following the instructions):

- WGET: copy and pasting downloads 6 month old version (works, but not even current stable, means you have to reinstall a later one if you find a bug)
- MAC: lotus homebrew installer doesn’t work on M1 Macs - Russell’s PR [https://github.com/filecoin-project/homebrew-lotus/issues/8](https://github.com/filecoin-project/homebrew-lotus/issues/8) fixes this
- SNAP: snap installation guidance doesn’t get to running client- filename isn’t ‘lotus’ (minor nit, but would be good to make it explicit), can’t find default wallet- see below

```bash
wallet f1tf7jfoxct33vjodvonklfldmwxrpxivgtvhmc5i - test wallet
```

Not only

```bash

ubuntu@ip-172-26-8-123:~$ lotus-filecoin.lotus wallet list
Address                                    Balance  Nonce  Default  
f1tf7jfoxct33vjodvonklfldmwxrpxivgtvhmc5i  0 FIL    0      X        
ubuntu@ip-172-26-8-123:~$ lotus-filecoin.lotus client deal
ERROR: checking from address balance: resolution lookup failed (f1tf7jfoxct33vjodvonklfldmwxrpxivgtvhmc5i): resolve address f1tf
7jfoxct33vjodvonklfldmwxrpxivgtvhmc5i: actor not found

ubuntu@ip-172-26-8-123:~$

```

But also sometimes this:

```bash

ubuntu@ip-172-26-5-33:~$ lotus-filecoin.lotus client deal
ERROR: failed to get default key: opening key 'default': key info not found
```

- AppImage: AppImage broken since November: [https://github.com/filecoin-project/lotus/issues/7733](https://github.com/filecoin-project/lotus/issues/7733) [https://github.com/filecoin-project/lotus/pull/7943](https://github.com/filecoin-project/lotus/pull/7943)
- pre-compiled binary: the .tar.gz needs a library linked on linux, no guidance on this in docs.  FIX: “ln -s /usr/lib/x86_64-linux-gnu/libhwloc.so /usr/lib/libhwloc.so.5"
- Only the Src build works as per instructions

None of these are dealbreakers, but they all add friction, that must manifest itself in dev frustration, reduced engagement, and longer time to get a node up and running.

**Comment by Annamarie2019** [comment]
Excellent summary above and some of the issues.

**Comment by johnnymatthews** [comment]
Can this be closed now @LexLuthr since we completed the Lotus Docs reorg?

**Comment by LexLuthr** [comment]
@johnnymatthews This is unrelated to the first reorg. This is about content verification and update. As you noted in my last PR, there are missing markdowns and incomplete info on some pages. We are verifying all the info and fixing it. Current focus is on SP section. We will start working on this after https://github.com/filecoin-project/lotus-docs/issues/77 is closed.

**Comment by johnnymatthews** [comment]
Fair enough. Thanks for re-opening!

**Comment by rjan90** [comment]
Closed in favour of this newly created issue: https://github.com/filecoin-project/lotus-docs/issues/360
